services:
  # Service Frontend
  - type: web
    name: ecole-moliere-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        value: https://ecole-moliere-api.onrender.com

  # Service Backend
  - type: web
    name: ecole-moliere-api
    env: java
    plan: free
    buildCommand: cd backend && ./mvnw package -DskipTests
    startCommand: cd backend && java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ecole-moliere-db
          property: connectionString

databases:
  - name: ecole-moliere-db
    databaseName: school_management
    plan: free
