spring:
  application:
    name: school-management
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/school_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: your-secret-key
  expiration: 86400000 # 24 hours

# Custom Application Properties
app:
  # File Upload
  upload:
    dir: uploads
    allowed-types: image/jpeg,image/png,application/pdf
    max-file-size: 5MB
  
  # Notification
  notification:
    email:
      enabled: true
    sms:
      enabled: false
  
  # Backup
  backup:
    enabled: true
    cron: "0 0 1 * * ?" # Every day at 1 AM
    path: backups

# Logging Configuration
logging:
  level:
    root: INFO
    com.abnsoft: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
  file:
    name: logs/school-management.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.abnsoft.school
  paths-to-match: /api/**
