spring:
  datasource:
    url: ${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key}
    expiration: 86400000

logging:
  level:
    root: INFO
    com.abnsoft: INFO
    org.flywaydb: DEBUG
